#+TITLE: My emacs doom configuration
#+AUTHOR: Song Pan
#+EMAIL: pan.song@dhs.sg

* Tasks
This section keeps track of what I plan to change.
** Make escape key work in vterm mode
* Configuration
** Lexical binding
Use lexical-binding. [[https://nullprogram.com/blog/2016/12/22/][Why?]]

#+BEGIN_QUOTE
Until Emacs 24.1 (June 2012), Elisp only had dynamically scoped variables,
a feature, mostly by accident, common to old lisp dialects. While dynamic
scope has some selective uses, it’s widely regarded as a mistake for local
variables, and virtually no other languages have adopted it.
#+END_QUOTE

#+begin_src elisp
;;; config.el --- -*- lexical-binding: t -*-
#+end_src
** Personal details
#+begin_src elisp
(setq user-full-name "Song Pan"
      user-mail-address "pan.song@dhs.sg")
#+end_src
** Org directory
The default doom comment said this should be done before org loads.
#+begin_src elisp
(setq org-directory "~/org/")
#+end_src
** Appearance
*** Line number
#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src
*** Theme
The default one.
#+begin_src elisp
(setq doom-theme 'doom-one)
#+end_src
*** Fonts
#+begin_src elisp
(setq doom-font (font-spec :family "Hasklig" :size 19 :weight 'semi-light))
#+end_src

*** Show matching paranthesis
#+begin_src elisp
(after! smartparens
  (show-smartparens-global-mode))
#+end_src
*** Org bullets
#+begin_src elisp
(use-package! org-bullets
  :after org
  :hook (org-mode . org-bullets-mode))
#+end_src
*** Ligatures
Taken from the ligatures doc.
#+begin_src elisp
(after! go-mode ; in this case the major mode and package named the same thing
  (set-ligatures! 'go-mode
    :def "func" ; function keyword
    :true "true" :false "false"
                                        ; this will replace not only definitions
                                        ; but coresponding functions aswell
    :int "int" :str "string"
    :float "float" :bool "bool"
    :for "for"
    :return "return" :yeild "yeild"))

(set-ligatures! 'MAJOR-MODE
  ;; Functional
  :lambda        "lambda keyword"
  :def           "function keyword"
  :composition   "composition"
  :map           "map/dictionary keyword"
  ;; Types
  :null          "null type"
  :true          "true keyword"
  :false         "false keyword"
  :int           "int keyword"
  :float         "float keyword"
  :str           "string keyword"
  :bool          "boolean keywork"
  :list          "list keyword"
  ;; Flow
  :not           "not operator"
  :in            "in operator"
  :not-in        "not in operator"
  :and           "and keyword"
  :or            "or keyword"
  :for           "for keyword"
  :some          "some keyword"
  :return        "return"
  :yield         "yeild"
  ;; Other
  :union         "Union keyword"
  :intersect     "Intersect keyword"
  :diff          "diff keyword"
  :tuple         "Tuple Keyword "
  :pipe          "Pipe Keyword" ;; FIXME: find a non-private char
  :dot           "Dot operator")
#+end_src

** Editing experience
*** Escape key
I am used to "fd". The only inconvenience I found is for variable name for
file descriptor. Luckily I don't write C that much.
#+begin_src elisp
(after! evil-escape
  (setq evil-escape-key-sequence "fd"))
#+end_src
*** Undo limit
#+begin_src elisp
(setq undo-limit 80000000)
#+end_src
*** Treat CamelCase as multiple words
#+begin_src elisp
(global-subword-mode 1)
#+end_src
*** Default to org mode
#+begin_src elisp
(setq-default major-mode 'org-mode)
#+end_src
*** Magit "gravatars"
Some random things I saw online. Not sure what it does actually.
#+begin_src elisp
(setq magit-revision-show-gravatars '("^Author:     " . "^Commit:     "))
#+end_src
** Moving around
*** Preview ivy buffers
#+begin_src elisp
(setq +ivy-buffer-preview t)
#+end_src
*** Display path in ivy-rich.
Ivy-rich has a [[https://github.com/Yevgnen/ivy-rich/issues/53][bug/feature]] that doesn't show a buffer's path if projectile
is enabled but the buffer is not in a project. This is a workaround to
fallback to absolute path in that case.
#+begin_src elisp
(after! ivy-rich
  (setq ivy-rich-path-style 'abbrev)
  (defadvice! ivy-rich-no-project-fallback (orig-fn candidate)
    :around #'ivy-rich--switch-buffer-root-and-filename
    (if-let ((result (funcall orig-fn candidate)))
        result
      (cons ""
            (expand-file-name (ivy-rich--switch-buffer-directory candidate))))))
#+end_src
** Editor flow optimisation
*** Prompt for a buffer when splitting windows
I almost always do this immediately afterwards anyway.
#+begin_src elisp
(defadvice! prompt-for-buffer (&rest _)
  :after '(evil-window-split evil-window-vsplit)
  (+ivy/switch-buffer))
#+end_src
*** Do not prompt "keep others" when manually saving
When saving perspectives, it always prompt me if I wanna keep others in
the same file. Yes I do. This is a failed attempt to always put =t= to
=keep-others=.
#+begin_src elisp
;; (defadvice! always-keep-others-when-saving-perspective (&optional fname phash name keep-others &rest rest-args)
;;   :filter-args #'persp-save-to-file-by-names
;;   '(fname phash name t rest-args))
#+end_src

** Features
*** Magit Forge setup
Note we need to follow [[https://magit.vc/manual/forge/Getting-Started.html#Getting-Started][forge manual]] to setup the token. Then use =M-x
forge-pull= to fetch the original repo.
#+begin_src elisp
(setq auth-sources '("~/.authinfo"))
#+end_src
** Custom Keybindings
*** Local leader
=SPC M= is too long.
#+begin_src elisp
(setq doom-localleader-key ",")
(setq doom-localleader-alt-key "M-,")
#+end_src
*** SPC TAB TAB to "last" workspace.
#+begin_src elisp
(map! :leader
      (:when (featurep! :ui workspaces)
       (:prefix-map ("TAB" . "workspace")
        :desc "Switch to last workspace" "TAB" #'+workspace/other)))
#+end_src
*** Window splitting
I like to use =-= to mean horizontal split and =/= to mean vertial.
#+begin_src elisp
(after! evil
  (define-key evil-window-map "/" 'evil-window-vsplit)
  (define-key evil-window-map "-" 'evil-window-split))
#+end_src
=SPC w -= was mapped to something else so we preserve it by remapping it
to =SPC w C--=
#+begin_src elisp
(define-key evil-window-map (kbd "C--") 'evil-window-decrease-height)
#+end_src
** Other
*** Auto save every buffer
#+begin_src elisp
(setq auto-save-default t)
#+end_src
*** Auto revert buffers from disk
Also checks version contorl info, whatever that means.
#+begin_src elisp
(use-package! autorevert
  :config
  (global-auto-revert-mode 1)
  (setq auto-revert-check-vc-info t))
#+end_src
*** Don't bother confirming killing process
#+begin_src elisp
(after! files
  (setq confirm-kill-processes nil))
#+end_src
*** Auto save when emacs is out of focus
Taken from[[http://ergoemacs.org/emacs/emacs_auto_save.html][ Emacs auto save]] 
#+begin_src elisp
(defun xah-save-all-unsaved ()
  "Save all unsaved files. no ask.
Version 2019-11-05"
  (interactive)
  (save-some-buffers t))

;; when switching out of emacs, all unsaved files will be saved
(add-hook 'focus-out-hook 'xah-save-all-unsaved)
#+end_src

* Notes
** Making magit push to github directly using ssh key
See [[file:other/ssh_config.org::*Github access][Github access]].
